services:
  rmq1:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rmq1
    hostname: rmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: log-collector-cookie
    volumes:
      - ./rabbitmq/rmq-data/rmq1:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rmq2:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rmq2
    hostname: rmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: log-collector-cookie
    volumes:
      - ./rabbitmq/rmq-data/rmq2:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rmq3:
    image: rabbitmq:4.2.3-management-alpine
    container_name: rmq3
    hostname: rmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: log-collector-cookie
    volumes:
      - ./rabbitmq/rmq-data/rmq3:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ch1:
    image: clickhouse/clickhouse-server:26.1-alpine
    container_name: ch1
    hostname: ch1
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./clickhouse/macro1.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./clickhouse/keeper1.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./clickhouse/ch-data/ch1-data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
  ch2:
    image: clickhouse/clickhouse-server:26.1-alpine
    container_name: ch2
    hostname: ch2
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./clickhouse/macro2.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./clickhouse/keeper2.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./clickhouse/ch-data/ch2-data:/var/lib/clickhouse
    ports:
      - '8124:8123'
      - '9001:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
    depends_on:
      ch1:
        condition: service_started
  ch3:
    image: clickhouse/clickhouse-server:26.1-alpine
    container_name: ch3
    hostname: ch3
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./clickhouse/macro3.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./clickhouse/keeper3.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./clickhouse/ch-data/ch3-data:/var/lib/clickhouse
    ports:
      - '8125:8123'
      - '9002:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
    depends_on:
      ch1:
        condition: service_started

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: collector
    hostname: collector
    restart: always
    environment:
       COLLECTOR_CONFIG_PATH: /etc/collector/config.yaml
       # variables from config file can be overrided with env variables
       HTTP_PORT: 8080
    volumes:
      - ./configs/config.yaml:/etc/collector/config.yaml:ro
    ports:
      - '8080:8080'
    depends_on:
      ch1:
        condition: service_started
      ch2:
        condition: service_started
      ch3:
        condition: service_started
      rmq1:
        condition: service_healthy
      rmq2:
        condition: service_healthy
      rmq3:
        condition: service_healthy


