loopback_users.guest = false
listeners.tcp.default = 5672

cluster_partition_handling = autoheal

cluster_formation.peer_discovery_backend = rabbitmq_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rmq1
cluster_formation.classic_config.nodes.2 = rabbit@rmq2
cluster_formation.classic_config.nodes.3 = rabbit@rmq3
