http:
  host: "0.0.0.0"
  port: 8080

clickhouse:
  database: "default"
  user: "default"
  password: "default"
  hosts:
    - "ch1:9000"
    - "ch2:9000"
    - "ch3:9000"

rabbitmq:
  username: "guest"
  password: "guest"
  queue_name: "log-entries"
  exchange_name: "logs"
  prefetch_count: 10
  brokers:
    - "rmq1:5672"
    - "rmq2:5672"
    - "rmq3:5672"

