http:
  host: "0.0.0.0"
  port: 8080

clickhouse:
  database: "logs_db"
  user: "default"
  password: "default"
  hosts:
    - "localhost:9000"
    - "localhost:9001"
    - "localhost:9002"

rabbitmq:
  brokers:
    - "localhost:5672"
    - "localhost:5673"
    - "localhost:5674"
  username: "guest"
  password: "guest"
  queue_name: "log-entries"
  prefetch_count: 10

metrics:
  host: "0.0.0.0"
  port: 8081
